2022-04-04 00:48:39,171 INFO: Open Forum Project [in /Users/pontusblomqvist/Documents/Programming/Git/OpenForumProject/app/__init__.py:48]
2022-04-04 00:52:45,229 INFO: Open Forum Project [in /Users/pontusblomqvist/Documents/Programming/Git/OpenForumProject/app/__init__.py:48]
2022-04-04 00:54:23,168 INFO: Open Forum Project [in /Users/pontusblomqvist/Documents/Programming/Git/OpenForumProject/app/__init__.py:48]
2022-04-04 00:54:27,156 ERROR: Exception on /api/create_password [PUT] [in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/pontusblomqvist/Documents/Programming/Git/OpenForumProject/app/api/users.py", line 52, in create_a_new_password
    user.user.set_password(data['password'])
AttributeError: 'User' object has no attribute 'user'
2022-04-04 00:54:33,619 ERROR: Exception on /api/create_password [PUT] [in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/pontusblomqvist/Documents/Programming/Git/OpenForumProject/app/api/users.py", line 52, in create_a_new_password
    user.user.set_password(data['password'])
AttributeError: 'User' object has no attribute 'user'
2022-04-04 00:55:09,469 INFO: Open Forum Project [in /Users/pontusblomqvist/Documents/Programming/Git/OpenForumProject/app/__init__.py:48]
2022-04-04 16:52:41,689 INFO: Open Forum Project [in /Users/pontusblomqvist/Documents/Programming/Git/OpenForumProject/app/__init__.py:56]
2022-04-04 16:52:52,920 ERROR: Exception on /api/resetpassword [PUT] [in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/pontusblomqvist/Documents/Programming/Git/OpenForumProject/app/api/users.py", line 37, in api_reset_password
    send_password_reset_email(user)
  File "/Users/pontusblomqvist/Documents/Programming/Git/OpenForumProject/app/auth/email.py", line 21, in send_password_reset_email
    text_body=render_template('email/reset_password.txt', user=user, token=token),
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/pontusblomqvist/Documents/Programming/Git/OpenForumProject/app/templates/email/reset_password.txt", line 5, in top-level template code
    {{ url_for('create_password', token=token, _external=True) }}
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/werkzeug/routing.py", line 2314, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'create_password' with values ['token']. Did you mean 'auth.create_password' instead?
2022-04-04 16:54:50,812 INFO: Open Forum Project [in /Users/pontusblomqvist/Documents/Programming/Git/OpenForumProject/app/__init__.py:56]
2022-04-04 16:54:59,419 ERROR: Exception on /api/resetpassword [PUT] [in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/pontusblomqvist/Documents/Programming/Git/OpenForumProject/app/api/users.py", line 37, in api_reset_password
    send_password_reset_email(user)
  File "/Users/pontusblomqvist/Documents/Programming/Git/OpenForumProject/app/auth/email.py", line 22, in send_password_reset_email
    html_body=render_template('email/reset_password.html', user=user, token=token))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/pontusblomqvist/Documents/Programming/Git/OpenForumProject/app/templates/email/reset_password.html", line 9, in top-level template code
    <p>{{ url_for('create_password', token=token, _external=True) }}</p>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/flask/helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/werkzeug/routing.py", line 2314, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'create_password' with values ['token']. Did you mean 'auth.create_password' instead?
2022-04-04 17:00:29,670 INFO: Open Forum Project [in /Users/pontusblomqvist/Documents/Programming/Git/OpenForumProject/app/__init__.py:56]
